/* React */
import React from 'react';

/* Styled */
import styled from 'styled-components';
import {HeaderButton} from "../../components/Button";

/* Styled Components */
const Container = styled.div`
    width: 1420px;
    margin: 0 auto;
`
const TitleSection = styled.div`
    padding-top: 420px;
    > * {
    margin-bottom: 20px;
    }
    > p:nth-of-type(2) {
    position: relative;
    left: 60px;
    }
    > button {
    float: right;
    margin-top: 20px;
    }
`
const TitleText = styled.p`    
    width: 1360px; 
    color: ${props => props.color};
    font-family: "Archivo";
    font-weight: ${props => props.fontWeight};
    font-size: ${props => props.fontSize};
    line-height: ${props => props.lineHeight};
    text-align: ${props => props.textAlign};
`

const CardSection = styled.div`
    clear: right;
    width: 100%;
    margin: 300px auto 0;
`

const Card = styled.div` 
    padding: 0 40px;
    margin-bottom: 59px;
    border-radius: 50px;
    background-color: #ffffff;
    box-shadow: 0px 10px 10px 10px rgba(18, 31, 56, 0.2);
    color: #000000;
    > p:nth-of-type(1) {
    font-family: Archivo;
    font-weight: 600;
    font-size: 32px;
    line-height: 389%;
    text-align: left;
    }
    >p:nth-of-type(2) {
    position: relative;
    left: 90px;
    width: 1300px;
    padding-bottom: 80px;
    font-family: Archivo;
    font-weight: 500;
    font-size: 20px;
    line-height: 215%;
    text-align: left;
    }
    >button {
    margin-bottom: 25px;
    }
`


/* Main Component */
const Home = () => {

    return (
        <Container>
            <TitleSection>
                <TitleText color={"#ffffff"} fontWeight={"700"} fontSize={"65px"} lineHeight={"192%"}
                           textAlign={"left"}>LAI protocol Build on PlatON</TitleText>
                <TitleText color={"#000000"} fontWeight={"600"} fontSize={"35px"} lineHeight={"125%"}
                           textAlign={"right"}>A decentralized lending ecosystem based on the native token LAT of the
                    PlatON Network. Participate in the ecology to earn stablecoin LAI and governance token
                    LAO.</TitleText>
                <HeaderButton width={"297px"} height={"68px"} color={"#ffffff"}
                              bgColor={"#000000"}>Go to App</HeaderButton>
            </TitleSection>
            <CardSection>
                <Card><p>What is LAI?</p>
                    <p>LAI is a kind of stablecoin designed to maintain the value of US dollar (1 LAI ≈ 1 USD). As long
                        as the native token LAT of PlatON is collaterald, the collaterald LAT can be appointed to the
                        validator of PlatON through the Collateralized Debt Position (CDP) of LAI. Therefore，the
                        security of the network and the capital efficiency of LAT can be ensured. In the future,
                        upcoming PRC-20s on PlatON or tokenized physical assets can be added into the list of
                        collaterald assets and issue the LAI.</p></Card>
                <Card><p>What is LAO?</p>
                    <p>LAO is a governance token and utility token that can claim the rights of the
                        LAI Protocol. Incentives generated by the protocol can be obtained through staking of LAO
                        tokens.</p></Card>
                <Card><p>What are the advantages of this protocol?</p>
                    <p>1.High capital efficiency <br/>
                    2. Low collateral ratio <br/>
                    3. Reducing the risk of stable liquidation through protocol liquidation model <br/>
                    4. Maintaining the security of PlatON network and issuing stable coins simultaneously without
                        competing with the main network of DeFi and PoS.</p>
                    <HeaderButton width={"297px"} height={"68px"} color={"#ffffff"}
                                  bgColor={"#000000"} fontSize={"18px"}>WhitePaper</HeaderButton>
                </Card>
            </CardSection>

        </Container>
    )
        ;
}

export default Home;